[package]
name = "gkr-protocol"
version = "0.1.0"
edition = "2021"

[dependencies]
ark-ff = "0.5"
ark-poly = "0.4"
ark-std = "0.4"

sum-check-protocol = { path = "../sum-check-protocol" }

thiserror = "1.0.31"

[dev-dependencies]
pretty_assertions = "1"
