[package]
name = "fiat-shamir"
version = "0.1.0"
edition = "2021"

[dependencies]
ark-serialize = "0.4" 
ark-ff = "0.5"
ark-poly = "0.4" 

sum-check-protocol = { path = "../sum-check-protocol" }

thiserror = "1.0.31"

[dev-dependencies]
ark-std = "0.4"

sha2 = "0.10.6"
